"""Glyph atlas (GENERATED by tools/build_art_blob.py from assets/font_atlas.png).

2 bits per pixel (0 empty, 1 shadow, 2 ink), zlib-compressed, base85.
"""

FONT_ATLAS_B85 = (
    "c-rk)%Z}SP5F`)e7ubU2uhCv|)&iDc`@{ikBhXhUmz;IT3}$lj0)xfaU%A~~B=xeLv4Pz^L<Eu^Q!GBa*ws|(zb{s)SFP$N`B7`7"
    "91Q()pT;?B<rl-XYRFh8O)lb=S{=`t|8n0A<6JvzwjSbK#8GMXgtL|n;R>pu_BnmqB}3f0i{p6`F5gf~Ej1~=HAWpPsW>hGNJh9f"
    "qh4sdtc!D26)UMI=4fevgOT;U>UwY03LWmyWStG>>GWuQJMEq<O*br`_a)g$lQiNAHJs=9Nfor56Xw}qTTLNT^0*f6=b8VhR7wAG"
    "t(I6vu4C8jX3XyODx-d<@&VUpvykIrmpa1u%2DCUmE~4!++F~#BoEQ@%U6chIvh4vl4}UZ$Oj#8I4b9)(z&5`W$_z#WUROq5r}=B"
    "JhfOyoWm$<@PVApf0HZ0sCp|nKSB1VlM!5jLr=g5o?Q}gG>M!5#GwL{U>w1lD$X-&r)wi_4fj7|x{O1g+?k)}4)a`NbdU2p@od7P"
    "eV^Q{@U+)5&ji0{4M!^jHCx$hHYXFl)k$P{uA_V7A}i?6(x`kc-`Fg*d?%Bez^LDs8h4iz2VRL|@-=#1$S<4984+z<jo3l|QDt34"
    "+$vM`vlix*WajdVnlyZH2{}W=EmGy4aV!Vv+I^#MS@0_Nhv0;C)EPq3@f&b;50^{JfK#fAOCs(NaXh7S5?b;FL92BivP_RV!tva}"
    "s+TO{XeU-#!0|n?BKQ6wm0>&^ao;1(m9k5+XYD-exIU&mLXz89^<@!p*xiQrB?-9ZuO1E|$)(h?hokl76|KmGFrWX_;r#fzXk@i+"
    "W_in-N+X;Z=8>X>(b*OBk9opoCLCj`(O#ExX-SoNIdSD$A(yJF)>JrfM+|Uc_>2}IEFEpsSnOcWI+*A30<I)?gHR}-0G0Ph?_jxv"
    "!VZoEUGq&MLygN_UBWR%J&ply8y0l=K}*chh!41MWqpaXr1j;Ch)c;a-!kcGBawu0JJpq2Oc|;@P?LSc(LjuI2uogWHM)!A9il0}"
    ";Dg5zASZ3df-aTN!noWHaU?gtSOIukgFwZCE|mx*#4!V0^E0x8F))l{Va<1B@BG+Q(n(%Mc5pm`QO1Z6BpF8p%KiBv5ET=TZsj-~"
    "<Ly!RDnXvU!pkn<))D8kEZ4SFJ$c^8wUvC51#oE(H-nr!Lu!85_=|kvZym>j=Nzf#97So~N=<Jzkat@faceMx;zKJ+xoeIAg&20e"
    "6eA=pE<t5#JEGLfR|zOq;#k_#rmSbP8@N{Cj&R&$glm3EAQC|bc}Go}s)uu395>;8q0m!$K?iv^!)6hca^MOus+bw6oL~2&dK>@T"
    "-s69rKIgxO^z(E&R#!h?DDX4Bve(c04jgWL$r!f6wGL&VKZCoqE_JqD-1kgyo)%jqaGM_P&4gs6Mjp-~;sBiQljh&pu0u0!hh8{$"
    "^5YTwkalr=C1erD1Eul|)5+ufJYW7ceVjt{abJ<n9faD=6Edk5w<%>mnLri9Ecx#{#iN6~qcpTC&d0XcmrVG;IovzWZ-vCqASo;m"
    "kBBun>1%^*ku~2eK4|!0WZP$-OXX;8ygC%uafSZBJ=`I)xw~+zK0G*P6(z#x(c=1rrA3L8wy85jJpbI+YBv^2^zEw(%ISzlLlHHp"
    "TwN6LxCv*%Ssd>bm+B847FF1|FLoBfS-AOTQS*7@lj#zt&A0<}mWxj<SB;K-y+)?!aVtD2ETeI~pxD8EEF=+Q-Rh#g{)mR7;n{|)"
    "u7g|cB@xSjV;R~HyIz|jtLxyr=zdRxe;mLloSm|0d?m~nM^cj+#{sOA2fkodz7j@b%kf&s>D4vYsO@c6TVBECzj*WbRlf(E^tkdD"
    "{gzSX_Ho4{JSs(W-&_WsDF&3Mb6CwUEZC_)Cx>T>F>bVG=FuzYwA3MY>K9J7#@p$61b$t_ak6!`7al1)s;k9)oZ?Y$#AyeU-(SJ4"
    "R<;wCNAv8+yFSjIKa0!yxOQskh4TxtkPhzMNS1ZNTi@x_9j}~U5N4i0P6r+d14`4`@>^y5;B`K~E7&|zULSm+Ts|0HZTi`kUy*5X"
    "q#+hBK8>U6uJ-Y0a~o%edLmqoa~5CMC8ZrIPR|^EoPNpFRi7|JTwu<g#pNC2br|qv@fglVoPY4Xh4ai2T%70lKDNVK$TNp?Co}8P"
    "_ZIG2X||8y#<|+`C_j~{Ol2xlnaWhAGL@-JWhzsd%2fWH@(;y~?yd"
)
